### ISSUE TITLE
Data not written in source directory

### ISSUE THREAD

**Issue by Flo354** [ovh/fossil#2]
Hi,

I just built Fossil & Beamium and started fossil with the following command 

> sudo ./build/fossil -d /opt/beamium/source

But nothing is written in the source directory... Does it has something to do with the file **cmd/root.go** where the line **//writer := writer.New** is commented. https://github.com/ovh/fossil/blob/master/cmd/root.go#L81

**Comment by StevenLeRoux** [comment]
Don't you see any listening TCP socket on the port 2003?

If it's running, you should be able to push data using graphite protocol to you flossil endpoint (by using collectd/statd or anything else. 

By default, without pushing data, Fossil won't write anything since it's just a proxy. If you need a companion that grabs host metrics, you can use [Noderig](https://github.com/ovh/noderig)

**Comment by Flo354** [comment]
Yes, logs are pushed without any problem: 

> ./build/fossil -d /opt/beamium/sources
INFO[0000] Fossil starting                              
INFO[0000] Listen on:2003                               
INFO[0000] Fossil started                               
INFO[0000] &{1514467605000000 servers.florian-debian.internalServerErrors.count map[0:servers 1:florian-debian 2:internalServerErrors 3:count] 0} 
INFO[0000] &{1514467605000000 servers.florian-debian.internalServerErrors.m1_rate map[0:servers 1:florian-debian 2:internalServerErrors 3:m1_rate] 0.00} 
INFO[0000] &{1514467605000000 servers.florian-debian.internalServerErrors.m5_rate map[0:servers 1:florian-debian 2:internalServerErrors 3:m5_rate] 0.00} 
INFO[0000] &{1514467605000000 servers.florian-debian.internalServerErrors.m15_rate map[3:m15_rate 0:servers 1:florian-debian 2:internalServerErrors] 0.00} 
INFO[0000] &{1514467605000000 servers.florian-debian.internalServerErrors.mean_rate map[0:servers 1:florian-debian 2:internalServerErrors 3:mean_rate] 0.00} 
INFO[0000] &{1514467605000000 servers.florian-debian.requests.count map[0:servers 1:florian-debian 2:requests 3:count] 5} 
INFO[0000] &{1514467605000000 servers.florian-debian.requests.m1_rate map[0:servers 1:florian-debian 2:requests 3:m1_rate] 0.00} 
INFO[0000] &{1514467605000000 servers.florian-debian.requests.m5_rate map[0:servers 1:florian-debian 2:requests 3:m5_rate] 0.07} 
INFO[0000] &{1514467605000000 servers.florian-debian.requests.m15_rate map[2:requests 3:m15_rate 0:servers 1:florian-debian] 0.42} 
INFO[0000] &{1514467605000000 servers.florian-debian.requests.mean_rate map[0:servers 1:florian-debian 2:requests 3:mean_rate] 0.01} 
INFO[0000] EOF

The problem is that no files are written in the directory **/opt/beamium/sources**. So no files are effectively sent to the graphite endpoint :(

EDIT: for my test, i set the **/opt/beamium/sources** writable by anyone

**Comment by StevenLeRoux** [comment]
You're right, this branch can't work.

I'm looking to fix it ASAP.

**Comment by Flo354** [comment]
Thanks, I wait.

In the meantime, we can find this in the README's dependencies section:

> glide https://github.com/bumptech/glide

It's not the right dependency. I assume you are talking about this glide: https://github.com/Masterminds/glide

**Comment by StevenLeRoux** [comment]
@Flo354 We applied a quick fix to make it work. Can you confirm it's ok for you now ?

**Comment by Flo354** [comment]
I just recompiled from latest sources, but still no output in the destination path.
On the other hand, **glide install** works now. It was broken before.

**Comment by StevenLeRoux** [comment]
@Flo354  it's fixed with #4 

Sorry, there have been a bad repo synchronisation :(

**Comment by Flo354** [comment]
Still no luck :(.
I wanted to tune the batch variable to see if it was related, but the new options **batch** and **timeout** are not registered.

> ./build/fossil -d /opt/beamium/sources/ -v --batch 1                                                                                           
Error: unknown flag: --batch
Usage:
  fossil [flags]
  fossil [command]
Available Commands:
  help        Help about any command
  version     Print the version number
Flags:
      --config string      config file to use
  -d, --directory string   directory to write metrics file (default "./sources")
  -h, --help               help for fossil
  -l, --listen string      listen address (default ":2003")
  -v, --verbose            verbose output
Use "fossil [command] --help" for more information about a command.
PANI[0000] unknown flag: --batch                        
panic: (*logrus.Entry) (0x81ae00,0xc4200187d0)
goroutine 1 [running]:
panic(0x81ae00, 0xc4200187d0)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
github.com/Sirupsen/logrus.Entry.log(0xc4200760a0, 0xc420013a40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc400000000, ...)
	/home/florian/go/src/github.com/Sirupsen/logrus/entry.go:128 +0x452
github.com/Sirupsen/logrus.(*Entry).Panic(0xc420018730, 0xc420155e38, 0x1, 0x1)
	/home/florian/go/src/github.com/Sirupsen/logrus/entry.go:173 +0x130
github.com/Sirupsen/logrus.(*Entry).Panicf(0xc420018730, 0x8274f2, 0x2, 0xc420155f18, 0x1, 0x1)
	/home/florian/go/src/github.com/Sirupsen/logrus/entry.go:221 +0x10a
github.com/Sirupsen/logrus.(*Logger).Panicf(0xc4200760a0, 0x8274f2, 0x2, 0xc420155f18, 0x1, 0x1)
	/home/florian/go/src/github.com/Sirupsen/logrus/logger.go:173 +0x94
github.com/Sirupsen/logrus.Panicf(0x8274f2, 0x2, 0xc420155f18, 0x1, 0x1)
	/home/florian/go/src/github.com/Sirupsen/logrus/exported.go:147 +0x5f
main.main()
	/opt/fossil/fossil.go:21 +0xb3

**Comment by FlorentinDUBOIS** [comment]
It's really weird I fresh re-clone the repository, install dependencies, compile it and I have no trouble.

What is the result of the following command?

```sh
git rev-parse HEAD
```
From my side, it is `e735d70f222375f882289618be72d57fcf64696e`.

**Comment by Flo354** [comment]
On my own it is the same: 

> git rev-parse HEAD                                                                                                                             
e735d70f222375f882289618be72d57fcf64696e

And it was also the same when compiling:

> make release
go build -ldflags "-X github.com/runabove/fossil/cmd.githash=e735d70f222375f882289618be72d57fcf64696e" -ldflags "-s -w" -o build/fossil fossil.go

**Comment by FlorentinDUBOIS** [comment]
What is your version of go?

**Comment by Flo354** [comment]
Okay, it was an issue with the cache! Works now...
Sorry for wasting your time

**Comment by FlorentinDUBOIS** [comment]
Don't worry 😄 !
